version: 2.2
jobs:
  build:
    docker:
      - image: circleci/openjdk:13-jdk-buster-browsers
    working_directory: ~/project/demo17
    steps:
      - checkout:
          - path: ~/project
      - restore_cache:
          key: maven-v1-{{ checksum "pom.xml" }}
      - run:
          name: ./mvnw install
          command: ./mvnw install
      - save_cache:
          key: maven-v1-{{ checksum "pom.xml" }}
          paths: ~/.m2
      - persist_to_workspace:
          root: .
          paths: .

  test:
    docker:
      - image: circleci/openjdk:13-jdk-buster-browsers
    working_directory: ~/project/demo17
    steps:
      - checkout:
          - path: ~/project
      - attach_workspace:
          at: .
      - run:
          name: unit test
          command: ./mvnw test

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: deploy to heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2.2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
